import '../models/stock_movement.dart';
import 'mock_items.dart';
import 'mock_reference.dart';
import 'mock_stores.dart';
import 'mock_suppliers.dart';

/// Movement history, newest first.
///
/// Covers roughly the last three weeks in detail and thins out further back —
/// which is what a real log looks like, and it means the date-range filter has
/// something to actually change.
///
/// All three movement types appear, including the waste and spoilage reasons
/// the usage report breaks down. `unitPrice` on deliveries is the price *paid*,
/// which occasionally differs from the supplier's listed price — that gap is
/// real in a kitchen and the Stock In screen lets it be edited.
final List<StockMovement> mockStockMovements = [
  // --- Today ------------------------------------------------------------------
  StockMovement(
    id: 'mv-001',
    storeId: StoreIds.sablon,
    itemId: ItemIds.jupiler,
    type: StockMovementType.stockOut,
    quantity: -3,
    reason: StockOutReason.sale,
    occurredAt: hoursAgo(2),
    userName: 'Thomas Peeters',
  ),
  StockMovement(
    id: 'mv-002',
    storeId: StoreIds.sablon,
    itemId: ItemIds.tomates,
    type: StockMovementType.stockOut,
    quantity: -6,
    reason: StockOutReason.sale,
    occurredAt: hoursAgo(3),
    userName: 'Sophie Lemmens',
  ),
  StockMovement(
    id: 'mv-003',
    storeId: StoreIds.sablon,
    itemId: ItemIds.frites,
    type: StockMovementType.stockIn,
    quantity: 60,
    supplierId: SupplierIds.grossisteCentral,
    unitPrice: 1.85,
    occurredAt: hoursAgo(4),
    userName: 'Sophie Lemmens',
  ),
  StockMovement(
    id: 'mv-004',
    storeId: StoreIds.sablon,
    itemId: ItemIds.poulet,
    type: StockMovementType.stockOut,
    quantity: -9,
    reason: StockOutReason.sale,
    occurredAt: hoursAgo(5),
    userName: 'Thomas Peeters',
  ),
  StockMovement(
    id: 'mv-005',
    storeId: StoreIds.sablon,
    itemId: ItemIds.beurre,
    type: StockMovementType.stockOut,
    quantity: -2.5,
    reason: StockOutReason.sale,
    occurredAt: hoursAgo(6),
    userName: 'Sophie Lemmens',
  ),
  StockMovement(
    id: 'mv-006',
    storeId: StoreIds.sablon,
    itemId: ItemIds.filetAmericain,
    type: StockMovementType.stockOut,
    quantity: -1.5,
    reason: StockOutReason.sale,
    occurredAt: hoursAgo(8),
    userName: 'Thomas Peeters',
  ),
  StockMovement(
    id: 'mv-007',
    storeId: StoreIds.sablon,
    itemId: ItemIds.cabillaud,
    type: StockMovementType.stockIn,
    quantity: 12,
    supplierId: SupplierIds.maree,
    unitPrice: 18.50,
    occurredAt: hoursAgo(11),
    userName: 'Amélie Vandenberghe',
    note: 'Arrivage du matin, très frais.',
  ),
  StockMovement(
    id: 'mv-008',
    storeId: StoreIds.sablon,
    itemId: ItemIds.moules,
    type: StockMovementType.stockIn,
    quantity: 40,
    supplierId: SupplierIds.maree,
    unitPrice: 6.40,
    occurredAt: hoursAgo(11),
    userName: 'Amélie Vandenberghe',
  ),
  StockMovement(
    id: 'mv-009',
    storeId: StoreIds.sablon,
    itemId: ItemIds.salade,
    type: StockMovementType.stockIn,
    quantity: 20,
    supplierId: SupplierIds.maraicher,
    unitPrice: 1.10,
    occurredAt: hoursAgo(20),
    userName: 'Sophie Lemmens',
  ),

  // --- Yesterday --------------------------------------------------------------
  StockMovement(
    id: 'mv-010',
    storeId: StoreIds.sablon,
    itemId: ItemIds.pommesTerre,
    type: StockMovementType.adjustment,
    quantity: -12,
    systemQuantity: 97,
    countedQuantity: 85,
    occurredAt: daysAgo(1),
    userName: 'Amélie Vandenberghe',
    note: 'Inventaire mensuel — écart probablement dû aux épluchures.',
  ),
  StockMovement(
    id: 'mv-011',
    storeId: StoreIds.sablon,
    itemId: ItemIds.persil,
    type: StockMovementType.stockOut,
    quantity: -2,
    reason: StockOutReason.spoilage,
    occurredAt: daysAgo(1),
    userName: 'Sophie Lemmens',
    note: 'Jauni, invendable.',
  ),
  StockMovement(
    id: 'mv-012',
    storeId: StoreIds.sablon,
    itemId: ItemIds.champignons,
    type: StockMovementType.stockOut,
    quantity: -3.5,
    reason: StockOutReason.sale,
    occurredAt: daysAgo(1),
    userName: 'Thomas Peeters',
  ),
  StockMovement(
    id: 'mv-013',
    storeId: StoreIds.sablon,
    itemId: ItemIds.carbonade,
    type: StockMovementType.stockIn,
    quantity: 18,
    supplierId: SupplierIds.boucherie,
    unitPrice: 14.20,
    occurredAt: daysAgo(1),
    userName: 'Amélie Vandenberghe',
  ),
  StockMovement(
    id: 'mv-014',
    storeId: StoreIds.sablon,
    itemId: ItemIds.creme,
    type: StockMovementType.stockIn,
    quantity: 12,
    supplierId: SupplierIds.cremerie,
    unitPrice: 3.60,
    occurredAt: daysAgo(1),
    userName: 'Sophie Lemmens',
  ),
  StockMovement(
    id: 'mv-015',
    storeId: StoreIds.sablon,
    itemId: ItemIds.lait,
    type: StockMovementType.stockIn,
    quantity: 24,
    supplierId: SupplierIds.cremerie,
    unitPrice: 1.05,
    occurredAt: daysAgo(1),
    userName: 'Sophie Lemmens',
  ),
  StockMovement(
    id: 'mv-016',
    storeId: StoreIds.sablon,
    itemId: ItemIds.boulettes,
    type: StockMovementType.stockOut,
    quantity: -35,
    reason: StockOutReason.sale,
    occurredAt: daysAgo(1),
    userName: 'Thomas Peeters',
  ),

  // --- 2 days -----------------------------------------------------------------
  StockMovement(
    id: 'mv-017',
    storeId: StoreIds.sablon,
    itemId: ItemIds.crevettes,
    type: StockMovementType.stockOut,
    quantity: -1.5,
    reason: StockOutReason.sale,
    occurredAt: daysAgo(2),
    userName: 'Thomas Peeters',
    note: 'Dernier stock écoulé.',
  ),
  StockMovement(
    id: 'mv-018',
    storeId: StoreIds.sablon,
    itemId: ItemIds.oignons,
    type: StockMovementType.stockOut,
    quantity: -5,
    reason: StockOutReason.sale,
    occurredAt: daysAgo(2),
    userName: 'Sophie Lemmens',
  ),
  StockMovement(
    id: 'mv-019',
    storeId: StoreIds.sablon,
    itemId: ItemIds.huileOlive,
    type: StockMovementType.stockOut,
    quantity: -3,
    reason: StockOutReason.sale,
    occurredAt: daysAgo(2),
    userName: 'Thomas Peeters',
  ),
  StockMovement(
    id: 'mv-020',
    storeId: StoreIds.sablon,
    itemId: ItemIds.carottes,
    type: StockMovementType.stockIn,
    quantity: 25,
    supplierId: SupplierIds.maraicher,
    unitPrice: 1.30,
    occurredAt: daysAgo(2),
    userName: 'Sophie Lemmens',
  ),
  StockMovement(
    id: 'mv-021',
    storeId: StoreIds.sablon,
    itemId: ItemIds.lard,
    type: StockMovementType.stockOut,
    quantity: -4,
    reason: StockOutReason.sale,
    occurredAt: daysAgo(2),
    userName: 'Thomas Peeters',
  ),
  StockMovement(
    id: 'mv-022',
    storeId: StoreIds.sablon,
    itemId: ItemIds.oeufs,
    type: StockMovementType.stockIn,
    quantity: 180,
    supplierId: SupplierIds.cremerie,
    unitPrice: 0.32,
    occurredAt: daysAgo(2),
    userName: 'Amélie Vandenberghe',
  ),

  // --- 3 days -----------------------------------------------------------------
  StockMovement(
    id: 'mv-023',
    storeId: StoreIds.sablon,
    itemId: ItemIds.citrons,
    type: StockMovementType.stockOut,
    quantity: -2.5,
    reason: StockOutReason.sale,
    occurredAt: daysAgo(3),
    userName: 'Sophie Lemmens',
  ),
  StockMovement(
    id: 'mv-024',
    storeId: StoreIds.sablon,
    itemId: ItemIds.gouda,
    type: StockMovementType.stockOut,
    quantity: -2.2,
    reason: StockOutReason.sale,
    occurredAt: daysAgo(3),
    userName: 'Thomas Peeters',
  ),
  StockMovement(
    id: 'mv-025',
    storeId: StoreIds.sablon,
    itemId: ItemIds.cola,
    type: StockMovementType.stockIn,
    quantity: 6,
    supplierId: SupplierIds.grossisteCentral,
    unitPrice: 18.75,
    occurredAt: daysAgo(3),
    userName: 'Sophie Lemmens',
  ),
  StockMovement(
    id: 'mv-026',
    storeId: StoreIds.sablon,
    itemId: ItemIds.eauPlate,
    type: StockMovementType.stockIn,
    quantity: 8,
    supplierId: SupplierIds.grossisteCentral,
    unitPrice: 7.90,
    occurredAt: daysAgo(3),
    userName: 'Sophie Lemmens',
  ),
  StockMovement(
    id: 'mv-027',
    storeId: StoreIds.sablon,
    itemId: ItemIds.tomates,
    type: StockMovementType.stockOut,
    quantity: -2,
    reason: StockOutReason.waste,
    occurredAt: daysAgo(3),
    userName: 'Sophie Lemmens',
    note: 'Caisse écrasée à la réception.',
  ),

  // --- 4–7 days ---------------------------------------------------------------
  StockMovement(
    id: 'mv-028',
    storeId: StoreIds.sablon,
    itemId: ItemIds.chimay,
    type: StockMovementType.stockIn,
    quantity: 4,
    supplierId: SupplierIds.brasseurs,
    unitPrice: 38.60,
    occurredAt: daysAgo(4),
    userName: 'Amélie Vandenberghe',
  ),
  StockMovement(
    id: 'mv-029',
    storeId: StoreIds.sablon,
    itemId: ItemIds.duvel,
    type: StockMovementType.stockIn,
    quantity: 3,
    supplierId: SupplierIds.brasseurs,
    unitPrice: 34.20,
    occurredAt: daysAgo(4),
    userName: 'Amélie Vandenberghe',
  ),
  StockMovement(
    id: 'mv-030',
    storeId: StoreIds.sablon,
    itemId: ItemIds.petitsPois,
    type: StockMovementType.stockIn,
    quantity: 20,
    supplierId: SupplierIds.grossisteCentral,
    unitPrice: 2.20,
    occurredAt: daysAgo(4),
    userName: 'Sophie Lemmens',
  ),
  StockMovement(
    id: 'mv-031',
    storeId: StoreIds.sablon,
    itemId: ItemIds.jambonArdenne,
    type: StockMovementType.stockOut,
    quantity: -2.5,
    reason: StockOutReason.sale,
    occurredAt: daysAgo(4),
    userName: 'Thomas Peeters',
  ),
  StockMovement(
    id: 'mv-032',
    storeId: StoreIds.sablon,
    itemId: ItemIds.mayonnaise,
    type: StockMovementType.stockIn,
    quantity: 10,
    supplierId: SupplierIds.grossisteCentral,
    unitPrice: 4.15,
    occurredAt: daysAgo(5),
    userName: 'Sophie Lemmens',
  ),
  StockMovement(
    id: 'mv-033',
    storeId: StoreIds.sablon,
    itemId: ItemIds.cafe,
    type: StockMovementType.stockOut,
    quantity: -4,
    reason: StockOutReason.sale,
    occurredAt: daysAgo(5),
    userName: 'Thomas Peeters',
  ),
  StockMovement(
    id: 'mv-034',
    storeId: StoreIds.sablon,
    itemId: ItemIds.farine,
    type: StockMovementType.stockIn,
    quantity: 50,
    supplierId: SupplierIds.grossisteCentral,
    unitPrice: 0.85,
    occurredAt: daysAgo(6),
    userName: 'Amélie Vandenberghe',
  ),
  StockMovement(
    id: 'mv-035',
    storeId: StoreIds.sablon,
    itemId: ItemIds.vinRouge,
    type: StockMovementType.stockIn,
    quantity: 24,
    supplierId: SupplierIds.horecaSelect,
    unitPrice: 6.80,
    occurredAt: daysAgo(7),
    userName: 'Amélie Vandenberghe',
  ),
  StockMovement(
    id: 'mv-036',
    storeId: StoreIds.sablon,
    itemId: ItemIds.moules,
    type: StockMovementType.stockOut,
    quantity: -8,
    reason: StockOutReason.spoilage,
    occurredAt: daysAgo(7),
    userName: 'Amélie Vandenberghe',
    note: 'Lot non conforme, retourné au fournisseur.',
  ),

  // --- 8–20 days --------------------------------------------------------------
  StockMovement(
    id: 'mv-037',
    storeId: StoreIds.sablon,
    itemId: ItemIds.riz,
    type: StockMovementType.stockIn,
    quantity: 30,
    supplierId: SupplierIds.grossisteCentral,
    unitPrice: 1.95,
    occurredAt: daysAgo(8),
    userName: 'Sophie Lemmens',
  ),
  StockMovement(
    id: 'mv-038',
    storeId: StoreIds.sablon,
    itemId: ItemIds.vinaigre,
    type: StockMovementType.stockIn,
    quantity: 12,
    supplierId: SupplierIds.grossisteCentral,
    unitPrice: 2.30,
    occurredAt: daysAgo(9),
    userName: 'Sophie Lemmens',
  ),
  StockMovement(
    id: 'mv-039',
    storeId: StoreIds.sablon,
    itemId: ItemIds.pommesTerre,
    type: StockMovementType.stockIn,
    quantity: 120,
    supplierId: SupplierIds.maraicher,
    unitPrice: 1.15,
    occurredAt: daysAgo(10),
    userName: 'Amélie Vandenberghe',
  ),
  StockMovement(
    id: 'mv-040',
    storeId: StoreIds.sablon,
    itemId: ItemIds.frites,
    type: StockMovementType.stockOut,
    quantity: -45,
    reason: StockOutReason.sale,
    occurredAt: daysAgo(11),
    userName: 'Thomas Peeters',
  ),
  StockMovement(
    id: 'mv-041',
    storeId: StoreIds.sablon,
    itemId: ItemIds.sel,
    type: StockMovementType.stockIn,
    quantity: 15,
    supplierId: SupplierIds.grossisteCentral,
    unitPrice: 0.70,
    occurredAt: daysAgo(12),
    userName: 'Sophie Lemmens',
  ),
  StockMovement(
    id: 'mv-042',
    storeId: StoreIds.sablon,
    itemId: ItemIds.poivre,
    type: StockMovementType.stockIn,
    quantity: 3,
    supplierId: SupplierIds.grossisteCentral,
    unitPrice: 24.00,
    occurredAt: daysAgo(12),
    userName: 'Sophie Lemmens',
  ),
  StockMovement(
    id: 'mv-043',
    storeId: StoreIds.sablon,
    itemId: ItemIds.carbonade,
    type: StockMovementType.stockOut,
    quantity: -6,
    reason: StockOutReason.transfer,
    occurredAt: daysAgo(14),
    userName: 'Marc Delvaux',
    note: 'Transféré vers Le Comptoir de Liège pour le week-end.',
  ),
  StockMovement(
    id: 'mv-044',
    storeId: StoreIds.sablon,
    itemId: ItemIds.gouda,
    type: StockMovementType.adjustment,
    quantity: 1.4,
    systemQuantity: 7.6,
    countedQuantity: 9,
    occurredAt: daysAgo(16),
    userName: 'Amélie Vandenberghe',
    note: 'Meule oubliée dans la chambre froide du bas.',
  ),
  StockMovement(
    id: 'mv-045',
    storeId: StoreIds.sablon,
    itemId: ItemIds.beurre,
    type: StockMovementType.stockIn,
    quantity: 15,
    supplierId: SupplierIds.cremerie,
    unitPrice: 7.20,
    occurredAt: daysAgo(16),
    userName: 'Sophie Lemmens',
  ),
  StockMovement(
    id: 'mv-046',
    storeId: StoreIds.sablon,
    itemId: ItemIds.poulet,
    type: StockMovementType.stockIn,
    quantity: 30,
    supplierId: SupplierIds.grossisteCentral,
    unitPrice: 12.40,
    occurredAt: daysAgo(18),
    userName: 'Amélie Vandenberghe',
    note: 'Dernière commande au prix précédent.',
  ),

  // --- Generated by confirming a goods receipt ---------------------------------
  //
  // These carry an order and a receipt reference; the manually entered
  // deliveries above do not. Both kinds are ordinary stock-in movements, which
  // is the point: receiving through an order and buying at the market on the
  // way in end up in the same log, and stock level still has exactly one
  // source of truth.
  //
  // From any of these a user can walk back: movement -> receipt -> order ->
  // supplier.
  StockMovement(
    id: 'mv-rcp-016-1',
    storeId: StoreIds.sablon,
    itemId: ItemIds.carbonade,
    type: StockMovementType.stockIn,
    quantity: 22,
    supplierId: SupplierIds.boucherie,
    unitPrice: 14.20,
    occurredAt: daysAgo(6),
    userName: 'Amélie Vandenberghe',
    orderId: 'po-2026-016',
    receiptId: 'gr-016-1',
  ),
  StockMovement(
    id: 'mv-rcp-016-2',
    storeId: StoreIds.sablon,
    itemId: ItemIds.lard,
    type: StockMovementType.stockIn,
    quantity: 4,
    supplierId: SupplierIds.boucherie,
    unitPrice: 9.80,
    occurredAt: daysAgo(6),
    userName: 'Amélie Vandenberghe',
    orderId: 'po-2026-016',
    receiptId: 'gr-016-1',
  ),
  StockMovement(
    id: 'mv-rcp-015-1',
    storeId: StoreIds.sablon,
    itemId: ItemIds.beurre,
    type: StockMovementType.stockIn,
    quantity: 15,
    supplierId: SupplierIds.cremerie,
    unitPrice: 7.20,
    occurredAt: daysAgo(11),
    userName: 'Marc Delvaux',
    orderId: 'po-2026-015',
    receiptId: 'gr-015-1',
  ),
  StockMovement(
    id: 'mv-rcp-015-2',
    storeId: StoreIds.sablon,
    itemId: ItemIds.creme,
    type: StockMovementType.stockIn,
    quantity: 24,
    supplierId: SupplierIds.cremerie,
    // The price on the delivery note, not the price on the order — which is
    // exactly why this movement is worth more than the order said it would be.
    unitPrice: 4.25,
    occurredAt: daysAgo(11),
    userName: 'Marc Delvaux',
    orderId: 'po-2026-015',
    receiptId: 'gr-015-1',
  ),
  StockMovement(
    id: 'mv-rcp-015-3',
    storeId: StoreIds.sablon,
    itemId: ItemIds.oeufs,
    type: StockMovementType.stockIn,
    quantity: 300,
    supplierId: SupplierIds.cremerie,
    unitPrice: 0.32,
    occurredAt: daysAgo(11),
    userName: 'Marc Delvaux',
    orderId: 'po-2026-015',
    receiptId: 'gr-015-1',
    note: 'Livraison incomplète — 60 pièces manquantes.',
  ),
  StockMovement(
    id: 'mv-rcp-015-4',
    storeId: StoreIds.sablon,
    itemId: ItemIds.gouda,
    type: StockMovementType.stockIn,
    quantity: 4,
    supplierId: SupplierIds.cremerie,
    unitPrice: 9.40,
    occurredAt: daysAgo(11),
    userName: 'Marc Delvaux',
    orderId: 'po-2026-015',
    receiptId: 'gr-015-1',
    note: 'Article non commandé.',
  ),
  StockMovement(
    id: 'mv-rcp-013-1',
    storeId: StoreIds.sablon,
    itemId: ItemIds.jupiler,
    type: StockMovementType.stockIn,
    quantity: 10,
    supplierId: SupplierIds.brasseurs,
    unitPrice: 21.50,
    occurredAt: daysAgo(23),
    userName: 'Sophie Lemmens',
    orderId: 'po-2026-013',
    receiptId: 'gr-013-1',
  ),
  StockMovement(
    id: 'mv-rcp-013-2',
    storeId: StoreIds.sablon,
    itemId: ItemIds.duvel,
    type: StockMovementType.stockIn,
    quantity: 4,
    supplierId: SupplierIds.brasseurs,
    unitPrice: 34.20,
    occurredAt: daysAgo(23),
    userName: 'Sophie Lemmens',
    orderId: 'po-2026-013',
    receiptId: 'gr-013-1',
  ),

  // --- Le Comptoir de Liège ---------------------------------------------------
  StockMovement(
    id: 'mv-lg-001',
    storeId: StoreIds.liege,
    itemId: ItemIds.liegeBoulets,
    type: StockMovementType.stockOut,
    quantity: -18,
    reason: StockOutReason.sale,
    occurredAt: hoursAgo(6),
    userName: 'Lucas Ferreira',
  ),
  StockMovement(
    id: 'mv-lg-002',
    storeId: StoreIds.liege,
    itemId: ItemIds.liegeJupiler,
    type: StockMovementType.stockOut,
    quantity: -4,
    reason: StockOutReason.sale,
    occurredAt: hoursAgo(9),
    userName: 'Lucas Ferreira',
  ),
  StockMovement(
    id: 'mv-lg-003',
    storeId: StoreIds.liege,
    itemId: ItemIds.liegeCafe,
    type: StockMovementType.stockOut,
    quantity: -3,
    reason: StockOutReason.sale,
    occurredAt: daysAgo(1),
    userName: 'Youssef El Amrani',
  ),
  StockMovement(
    id: 'mv-lg-004',
    storeId: StoreIds.liege,
    itemId: ItemIds.liegeFrites,
    type: StockMovementType.stockIn,
    quantity: 40,
    supplierId: SupplierIds.liegeGrossiste,
    unitPrice: 1.90,
    occurredAt: daysAgo(1),
    userName: 'Youssef El Amrani',
  ),
  StockMovement(
    id: 'mv-lg-005',
    storeId: StoreIds.liege,
    itemId: ItemIds.liegeOignons,
    type: StockMovementType.stockOut,
    quantity: -4,
    reason: StockOutReason.sale,
    occurredAt: daysAgo(2),
    userName: 'Lucas Ferreira',
  ),
  StockMovement(
    id: 'mv-lg-006',
    storeId: StoreIds.liege,
    itemId: ItemIds.liegeSirop,
    type: StockMovementType.stockOut,
    quantity: -1,
    reason: StockOutReason.sale,
    occurredAt: daysAgo(3),
    userName: 'Youssef El Amrani',
  ),
];
