-- GENERATED by tool/generate_server_schema.py from lib/data/database/migrations/drift_schema_v16.json.
-- Do not edit by hand; a later change is a new migration.
--
-- The server's copy of the app's synced tables (SYNC_PLAN.md, Phase 3,
-- steps 3.2, 3.3, 3.5 and 3.6).
--
-- - Same columns and keys as the app, minus the two stock figures every
--   device recomputes (`items.quantity`, `items.average_cost`).
-- - `server_seq` is stamped from one sequence on every insert and update.
--   A device remembers the last number it saw and pulls what came after.
-- - The only foreign key is to `stores`, which is what access hangs on. The
--   app guarantees the others, and on a server fed by several offline
--   devices a child can legitimately arrive before a later edit of its
--   parent (an attendance linked to a pay period queued afterwards).
-- - Clients can read (row level security) but not write: every write goes
--   through `push_changes`, so its rules cannot be bypassed.

create sequence private.sync_seq;

create function private.stamp_server_seq() returns trigger
  language plpgsql set search_path = ''
as $$
begin
  new.server_seq := nextval('private.sync_seq');
  return new;
end;
$$;

-- The newest change number per store. Devices listen to this one small table
-- (realtime) rather than to twenty, and pull when it moves.
create table public.store_changes (
  store_id text primary key,
  last_seq bigint not null
);
alter table public.store_changes enable row level security;
revoke insert, update, delete, truncate on public.store_changes
  from anon, authenticated;
revoke all on public.store_changes from anon;

create function private.note_store_change() returns trigger
  language plpgsql security definer set search_path = ''
as $$
declare
  v_store text := to_jsonb(new) ->> tg_argv[0];
begin
  insert into public.store_changes (store_id, last_seq)
    values (v_store, new.server_seq)
  on conflict (store_id) do update
    set last_seq = greatest(public.store_changes.last_seq, excluded.last_seq);
  return null;
end;
$$;

-- Which tables `push_changes` accepts, their keys, and where their store is.
create table private.sync_tables (
  name text primary key,
  key_columns text[] not null,
  store_column text not null
);


create table public.stores (
  updated_at timestamptz not null,
  deleted_at timestamptz,
  id text not null,
  name text not null,
  address_line text not null,
  postal_code text not null,
  city text not null,
  phone text not null,
  created_at timestamptz not null,
  vat_number text,
  image_asset text,
  stale_partial_order_days bigint not null,
  max_break_minutes bigint not null,
  notify_low_stock boolean not null,
  notify_price_change boolean not null,
  notify_large_adjustment boolean not null,
  notify_deliveries boolean not null,
  notify_busy_days boolean not null,
  busy_weekdays text not null,
  busy_reminder_days bigint not null,
  organization_id uuid not null references public.organizations (id),
  server_seq bigint not null,
  updated_by_device text,
  primary key (id)
);
create index stores_pull on public.stores (organization_id, server_seq);
create trigger stores_seq before insert or update on public.stores
  for each row execute function private.stamp_server_seq();
create trigger stores_store_change after insert or update on public.stores
  for each row execute function private.note_store_change('id');
alter table public.stores enable row level security;
create policy stores_read on public.stores for select to authenticated
  using (organization_id = private.my_organization());
revoke insert, update, delete, truncate on public.stores
  from anon, authenticated;
revoke all on public.stores from anon;
insert into private.sync_tables (name, key_columns, store_column)
  values ('stores', array['id'],
          'id');

-- Whether the caller may see and change this store's data: the store belongs
-- to the caller's organization.
create function private.can_access_store(p_store_id text) returns boolean
  language sql stable security definer set search_path = ''
as $$
  select exists (
    select 1 from public.stores s
     where s.id = p_store_id
       and s.organization_id = private.my_organization()
  )
$$;

create policy store_changes_read on public.store_changes
  for select to authenticated
  using (private.can_access_store(store_id));

alter publication supabase_realtime add table public.store_changes;


create table public.categories (
  updated_at timestamptz not null,
  deleted_at timestamptz,
  id text not null,
  store_id text not null references public.stores (id),
  name text not null,
  server_seq bigint not null,
  updated_by_device text,
  primary key (id)
);
create index categories_pull on public.categories (store_id, server_seq);
create trigger categories_seq before insert or update on public.categories
  for each row execute function private.stamp_server_seq();
create trigger categories_store_change after insert or update on public.categories
  for each row execute function private.note_store_change('store_id');
alter table public.categories enable row level security;
create policy categories_read on public.categories for select to authenticated
  using (private.can_access_store(store_id));
revoke insert, update, delete, truncate on public.categories
  from anon, authenticated;
revoke all on public.categories from anon;
insert into private.sync_tables (name, key_columns, store_column)
  values ('categories', array['id'],
          'store_id');

create table public.units (
  updated_at timestamptz not null,
  deleted_at timestamptz,
  id text not null,
  store_id text not null references public.stores (id),
  name text not null,
  abbreviation text not null,
  server_seq bigint not null,
  updated_by_device text,
  primary key (id)
);
create index units_pull on public.units (store_id, server_seq);
create trigger units_seq before insert or update on public.units
  for each row execute function private.stamp_server_seq();
create trigger units_store_change after insert or update on public.units
  for each row execute function private.note_store_change('store_id');
alter table public.units enable row level security;
create policy units_read on public.units for select to authenticated
  using (private.can_access_store(store_id));
revoke insert, update, delete, truncate on public.units
  from anon, authenticated;
revoke all on public.units from anon;
insert into private.sync_tables (name, key_columns, store_column)
  values ('units', array['id'],
          'store_id');

create table public.items (
  deleted_at timestamptz,
  id text not null,
  store_id text not null references public.stores (id),
  name text not null,
  category_id text not null,
  unit_id text not null,
  low_stock_threshold double precision not null,
  max_stock double precision not null,
  holiday_low_stock_threshold double precision,
  updated_at timestamptz not null,
  baseline_quantity double precision not null,
  baseline_average_cost double precision,
  default_supplier_id text,
  barcode text,
  note text,
  image_path text,
  server_seq bigint not null,
  updated_by_device text,
  primary key (id)
);
create index items_pull on public.items (store_id, server_seq);
create trigger items_seq before insert or update on public.items
  for each row execute function private.stamp_server_seq();
create trigger items_store_change after insert or update on public.items
  for each row execute function private.note_store_change('store_id');
alter table public.items enable row level security;
create policy items_read on public.items for select to authenticated
  using (private.can_access_store(store_id));
revoke insert, update, delete, truncate on public.items
  from anon, authenticated;
revoke all on public.items from anon;
insert into private.sync_tables (name, key_columns, store_column)
  values ('items', array['id'],
          'store_id');

create table public.suppliers (
  updated_at timestamptz not null,
  deleted_at timestamptz,
  id text not null,
  store_id text not null references public.stores (id),
  name text not null,
  contact_name text not null,
  email text not null,
  phone text not null,
  address_line text not null,
  postal_code text not null,
  city text not null,
  note text,
  server_seq bigint not null,
  updated_by_device text,
  primary key (id)
);
create index suppliers_pull on public.suppliers (store_id, server_seq);
create trigger suppliers_seq before insert or update on public.suppliers
  for each row execute function private.stamp_server_seq();
create trigger suppliers_store_change after insert or update on public.suppliers
  for each row execute function private.note_store_change('store_id');
alter table public.suppliers enable row level security;
create policy suppliers_read on public.suppliers for select to authenticated
  using (private.can_access_store(store_id));
revoke insert, update, delete, truncate on public.suppliers
  from anon, authenticated;
revoke all on public.suppliers from anon;
insert into private.sync_tables (name, key_columns, store_column)
  values ('suppliers', array['id'],
          'store_id');

create table public.supplier_prices (
  updated_at timestamptz not null,
  deleted_at timestamptz,
  id text not null,
  store_id text not null references public.stores (id),
  item_id text not null,
  supplier_id text not null,
  price_per_unit double precision not null,
  effective_date timestamptz not null,
  is_default boolean not null,
  server_seq bigint not null,
  updated_by_device text,
  primary key (id)
);
create index supplier_prices_pull on public.supplier_prices (store_id, server_seq);
create trigger supplier_prices_seq before insert or update on public.supplier_prices
  for each row execute function private.stamp_server_seq();
create trigger supplier_prices_store_change after insert or update on public.supplier_prices
  for each row execute function private.note_store_change('store_id');
alter table public.supplier_prices enable row level security;
create policy supplier_prices_read on public.supplier_prices for select to authenticated
  using (private.can_access_store(store_id));
revoke insert, update, delete, truncate on public.supplier_prices
  from anon, authenticated;
revoke all on public.supplier_prices from anon;
insert into private.sync_tables (name, key_columns, store_column)
  values ('supplier_prices', array['id'],
          'store_id');

create table public.price_history (
  updated_at timestamptz not null,
  deleted_at timestamptz,
  id text not null,
  store_id text not null references public.stores (id),
  item_id text not null,
  supplier_id text not null,
  old_price double precision not null,
  new_price double precision not null,
  changed_at timestamptz not null,
  changed_by_name text not null,
  server_seq bigint not null,
  updated_by_device text,
  primary key (id)
);
create index price_history_pull on public.price_history (store_id, server_seq);
create trigger price_history_seq before insert or update on public.price_history
  for each row execute function private.stamp_server_seq();
create trigger price_history_store_change after insert or update on public.price_history
  for each row execute function private.note_store_change('store_id');
alter table public.price_history enable row level security;
create policy price_history_read on public.price_history for select to authenticated
  using (private.can_access_store(store_id));
revoke insert, update, delete, truncate on public.price_history
  from anon, authenticated;
revoke all on public.price_history from anon;
insert into private.sync_tables (name, key_columns, store_column)
  values ('price_history', array['id'],
          'store_id');

create table public.stock_movements (
  updated_at timestamptz not null,
  deleted_at timestamptz,
  id text not null,
  store_id text not null references public.stores (id),
  item_id text not null,
  type text not null,
  quantity double precision not null,
  occurred_at timestamptz not null,
  user_name text not null,
  employee_id text,
  supplier_id text,
  unit_price double precision,
  reason text,
  system_quantity double precision,
  counted_quantity double precision,
  unit_cost double precision,
  average_cost_after double precision,
  order_id text,
  receipt_id text,
  note text,
  in_baseline boolean not null,
  server_seq bigint not null,
  updated_by_device text,
  primary key (id)
);
create index stock_movements_pull on public.stock_movements (store_id, server_seq);
create trigger stock_movements_seq before insert or update on public.stock_movements
  for each row execute function private.stamp_server_seq();
create trigger stock_movements_store_change after insert or update on public.stock_movements
  for each row execute function private.note_store_change('store_id');
alter table public.stock_movements enable row level security;
create policy stock_movements_read on public.stock_movements for select to authenticated
  using (private.can_access_store(store_id));
revoke insert, update, delete, truncate on public.stock_movements
  from anon, authenticated;
revoke all on public.stock_movements from anon;
insert into private.sync_tables (name, key_columns, store_column)
  values ('stock_movements', array['id'],
          'store_id');

create table public.purchase_orders (
  updated_at timestamptz not null,
  deleted_at timestamptz,
  id text not null,
  store_id text not null references public.stores (id),
  supplier_id text not null,
  reference text not null,
  status text not null,
  created_at timestamptz not null,
  sent_at timestamptz,
  closed_at timestamptz,
  note text,
  server_seq bigint not null,
  updated_by_device text,
  primary key (id)
);
create index purchase_orders_pull on public.purchase_orders (store_id, server_seq);
create trigger purchase_orders_seq before insert or update on public.purchase_orders
  for each row execute function private.stamp_server_seq();
create trigger purchase_orders_store_change after insert or update on public.purchase_orders
  for each row execute function private.note_store_change('store_id');
alter table public.purchase_orders enable row level security;
create policy purchase_orders_read on public.purchase_orders for select to authenticated
  using (private.can_access_store(store_id));
revoke insert, update, delete, truncate on public.purchase_orders
  from anon, authenticated;
revoke all on public.purchase_orders from anon;
insert into private.sync_tables (name, key_columns, store_column)
  values ('purchase_orders', array['id'],
          'store_id');

create table public.purchase_order_lines (
  updated_at timestamptz not null,
  deleted_at timestamptz,
  id text not null,
  store_id text not null references public.stores (id),
  order_id text not null,
  item_id text not null,
  quantity_ordered double precision not null,
  quantity_received double precision not null,
  unit_price double precision not null,
  closed_short boolean not null,
  position bigint not null,
  server_seq bigint not null,
  updated_by_device text,
  primary key (id)
);
create index purchase_order_lines_pull on public.purchase_order_lines (store_id, server_seq);
create trigger purchase_order_lines_seq before insert or update on public.purchase_order_lines
  for each row execute function private.stamp_server_seq();
create trigger purchase_order_lines_store_change after insert or update on public.purchase_order_lines
  for each row execute function private.note_store_change('store_id');
alter table public.purchase_order_lines enable row level security;
create policy purchase_order_lines_read on public.purchase_order_lines for select to authenticated
  using (private.can_access_store(store_id));
revoke insert, update, delete, truncate on public.purchase_order_lines
  from anon, authenticated;
revoke all on public.purchase_order_lines from anon;
insert into private.sync_tables (name, key_columns, store_column)
  values ('purchase_order_lines', array['id'],
          'store_id');

create table public.goods_receipts (
  updated_at timestamptz not null,
  deleted_at timestamptz,
  id text not null,
  order_id text not null,
  store_id text not null references public.stores (id),
  received_at timestamptz not null,
  received_by_name text not null,
  received_by_employee_id text,
  note text,
  server_seq bigint not null,
  updated_by_device text,
  primary key (id)
);
create index goods_receipts_pull on public.goods_receipts (store_id, server_seq);
create trigger goods_receipts_seq before insert or update on public.goods_receipts
  for each row execute function private.stamp_server_seq();
create trigger goods_receipts_store_change after insert or update on public.goods_receipts
  for each row execute function private.note_store_change('store_id');
alter table public.goods_receipts enable row level security;
create policy goods_receipts_read on public.goods_receipts for select to authenticated
  using (private.can_access_store(store_id));
revoke insert, update, delete, truncate on public.goods_receipts
  from anon, authenticated;
revoke all on public.goods_receipts from anon;
insert into private.sync_tables (name, key_columns, store_column)
  values ('goods_receipts', array['id'],
          'store_id');

create table public.goods_receipt_lines (
  updated_at timestamptz not null,
  deleted_at timestamptz,
  id text not null,
  store_id text not null references public.stores (id),
  receipt_id text not null,
  item_id text not null,
  quantity_ordered double precision not null,
  quantity_received double precision not null,
  actual_unit_price double precision not null,
  closed_short boolean not null,
  was_unordered boolean not null,
  note text,
  position bigint not null,
  server_seq bigint not null,
  updated_by_device text,
  primary key (id)
);
create index goods_receipt_lines_pull on public.goods_receipt_lines (store_id, server_seq);
create trigger goods_receipt_lines_seq before insert or update on public.goods_receipt_lines
  for each row execute function private.stamp_server_seq();
create trigger goods_receipt_lines_store_change after insert or update on public.goods_receipt_lines
  for each row execute function private.note_store_change('store_id');
alter table public.goods_receipt_lines enable row level security;
create policy goods_receipt_lines_read on public.goods_receipt_lines for select to authenticated
  using (private.can_access_store(store_id));
revoke insert, update, delete, truncate on public.goods_receipt_lines
  from anon, authenticated;
revoke all on public.goods_receipt_lines from anon;
insert into private.sync_tables (name, key_columns, store_column)
  values ('goods_receipt_lines', array['id'],
          'store_id');

create table public.notifications (
  updated_at timestamptz not null,
  deleted_at timestamptz,
  id text not null,
  store_id text not null references public.stores (id),
  kind text not null,
  title text not null,
  body text not null,
  created_at timestamptz not null,
  is_read boolean not null,
  related_item_id text,
  related_supplier_id text,
  server_seq bigint not null,
  updated_by_device text,
  primary key (id)
);
create index notifications_pull on public.notifications (store_id, server_seq);
create trigger notifications_seq before insert or update on public.notifications
  for each row execute function private.stamp_server_seq();
create trigger notifications_store_change after insert or update on public.notifications
  for each row execute function private.note_store_change('store_id');
alter table public.notifications enable row level security;
create policy notifications_read on public.notifications for select to authenticated
  using (private.can_access_store(store_id));
revoke insert, update, delete, truncate on public.notifications
  from anon, authenticated;
revoke all on public.notifications from anon;
insert into private.sync_tables (name, key_columns, store_column)
  values ('notifications', array['id'],
          'store_id');

create table public.employees (
  updated_at timestamptz not null,
  deleted_at timestamptz,
  id text not null,
  store_id text not null references public.stores (id),
  first_name text not null,
  last_name text not null,
  pin text not null,
  phone text not null,
  email text not null,
  photo_asset text,
  hire_date timestamptz not null,
  role text not null,
  pay double precision not null,
  created_at timestamptz not null,
  archived_at timestamptz,
  server_seq bigint not null,
  updated_by_device text,
  primary key (id)
);
create index employees_pull on public.employees (store_id, server_seq);
create trigger employees_seq before insert or update on public.employees
  for each row execute function private.stamp_server_seq();
create trigger employees_store_change after insert or update on public.employees
  for each row execute function private.note_store_change('store_id');
alter table public.employees enable row level security;
create policy employees_read on public.employees for select to authenticated
  using (private.can_access_store(store_id));
revoke insert, update, delete, truncate on public.employees
  from anon, authenticated;
revoke all on public.employees from anon;
insert into private.sync_tables (name, key_columns, store_column)
  values ('employees', array['id'],
          'store_id');

create table public.employee_credentials (
  updated_at timestamptz not null,
  deleted_at timestamptz,
  id text not null,
  store_id text not null references public.stores (id),
  employee_id text not null,
  password_hash text not null,
  failed_attempts bigint not null,
  locked_until timestamptz,
  last_login_at timestamptz,
  server_seq bigint not null,
  updated_by_device text,
  primary key (id)
);
create index employee_credentials_pull on public.employee_credentials (store_id, server_seq);
create trigger employee_credentials_seq before insert or update on public.employee_credentials
  for each row execute function private.stamp_server_seq();
create trigger employee_credentials_store_change after insert or update on public.employee_credentials
  for each row execute function private.note_store_change('store_id');
alter table public.employee_credentials enable row level security;
create policy employee_credentials_read on public.employee_credentials for select to authenticated
  using (private.can_access_store(store_id));
revoke insert, update, delete, truncate on public.employee_credentials
  from anon, authenticated;
revoke all on public.employee_credentials from anon;
insert into private.sync_tables (name, key_columns, store_column)
  values ('employee_credentials', array['id'],
          'store_id');

create table public.payroll_periods (
  updated_at timestamptz not null,
  deleted_at timestamptz,
  id text not null,
  employee_id text not null,
  store_id text not null references public.stores (id),
  start_date timestamptz not null,
  end_date timestamptz not null,
  worked_days bigint not null,
  total_worked_hours double precision not null,
  applied_rate double precision not null,
  computed_amount double precision not null,
  status text not null,
  paid_by_employee_id text,
  paid_at timestamptz,
  created_at timestamptz not null,
  server_seq bigint not null,
  updated_by_device text,
  primary key (id)
);
create index payroll_periods_pull on public.payroll_periods (store_id, server_seq);
create trigger payroll_periods_seq before insert or update on public.payroll_periods
  for each row execute function private.stamp_server_seq();
create trigger payroll_periods_store_change after insert or update on public.payroll_periods
  for each row execute function private.note_store_change('store_id');
alter table public.payroll_periods enable row level security;
create policy payroll_periods_read on public.payroll_periods for select to authenticated
  using (private.can_access_store(store_id));
revoke insert, update, delete, truncate on public.payroll_periods
  from anon, authenticated;
revoke all on public.payroll_periods from anon;
insert into private.sync_tables (name, key_columns, store_column)
  values ('payroll_periods', array['id'],
          'store_id');

create table public.attendances (
  updated_at timestamptz not null,
  deleted_at timestamptz,
  id text not null,
  store_id text not null references public.stores (id),
  employee_id text not null,
  date timestamptz not null,
  status text not null,
  max_break_minutes bigint,
  payroll_period_id text,
  server_seq bigint not null,
  updated_by_device text,
  primary key (id)
);
create index attendances_pull on public.attendances (store_id, server_seq);
create trigger attendances_seq before insert or update on public.attendances
  for each row execute function private.stamp_server_seq();
create trigger attendances_store_change after insert or update on public.attendances
  for each row execute function private.note_store_change('store_id');
alter table public.attendances enable row level security;
create policy attendances_read on public.attendances for select to authenticated
  using (private.can_access_store(store_id));
revoke insert, update, delete, truncate on public.attendances
  from anon, authenticated;
revoke all on public.attendances from anon;
insert into private.sync_tables (name, key_columns, store_column)
  values ('attendances', array['id'],
          'store_id');

create table public.attendance_sessions (
  updated_at timestamptz not null,
  deleted_at timestamptz,
  id text not null,
  store_id text not null references public.stores (id),
  attendance_id text not null,
  position bigint not null,
  clock_in_at timestamptz not null,
  clock_out_at timestamptz,
  server_seq bigint not null,
  updated_by_device text,
  primary key (id)
);
create index attendance_sessions_pull on public.attendance_sessions (store_id, server_seq);
create trigger attendance_sessions_seq before insert or update on public.attendance_sessions
  for each row execute function private.stamp_server_seq();
create trigger attendance_sessions_store_change after insert or update on public.attendance_sessions
  for each row execute function private.note_store_change('store_id');
alter table public.attendance_sessions enable row level security;
create policy attendance_sessions_read on public.attendance_sessions for select to authenticated
  using (private.can_access_store(store_id));
revoke insert, update, delete, truncate on public.attendance_sessions
  from anon, authenticated;
revoke all on public.attendance_sessions from anon;
insert into private.sync_tables (name, key_columns, store_column)
  values ('attendance_sessions', array['id'],
          'store_id');

create table public.attendance_pauses (
  updated_at timestamptz not null,
  deleted_at timestamptz,
  id text not null,
  store_id text not null references public.stores (id),
  session_id text not null,
  position bigint not null,
  start_at timestamptz not null,
  end_at timestamptz,
  server_seq bigint not null,
  updated_by_device text,
  primary key (id)
);
create index attendance_pauses_pull on public.attendance_pauses (store_id, server_seq);
create trigger attendance_pauses_seq before insert or update on public.attendance_pauses
  for each row execute function private.stamp_server_seq();
create trigger attendance_pauses_store_change after insert or update on public.attendance_pauses
  for each row execute function private.note_store_change('store_id');
alter table public.attendance_pauses enable row level security;
create policy attendance_pauses_read on public.attendance_pauses for select to authenticated
  using (private.can_access_store(store_id));
revoke insert, update, delete, truncate on public.attendance_pauses
  from anon, authenticated;
revoke all on public.attendance_pauses from anon;
insert into private.sync_tables (name, key_columns, store_column)
  values ('attendance_pauses', array['id'],
          'store_id');

create table public.busy_dates (
  updated_at timestamptz not null,
  deleted_at timestamptz,
  store_id text not null references public.stores (id),
  day text not null,
  server_seq bigint not null,
  updated_by_device text,
  primary key (store_id, day)
);
create index busy_dates_pull on public.busy_dates (store_id, server_seq);
create trigger busy_dates_seq before insert or update on public.busy_dates
  for each row execute function private.stamp_server_seq();
create trigger busy_dates_store_change after insert or update on public.busy_dates
  for each row execute function private.note_store_change('store_id');
alter table public.busy_dates enable row level security;
create policy busy_dates_read on public.busy_dates for select to authenticated
  using (private.can_access_store(store_id));
revoke insert, update, delete, truncate on public.busy_dates
  from anon, authenticated;
revoke all on public.busy_dates from anon;
insert into private.sync_tables (name, key_columns, store_column)
  values ('busy_dates', array['store_id', 'day'],
          'store_id');

-- Everything in one store that changed after `p_after`, oldest first, at
-- most `p_limit` rows. The caller saves `next_after` and asks again while
-- `has_more` is true. Deleted rows come back too (with `deleted_at` set):
-- that is how a device learns about a delete.
create function public.pull_changes(
  p_store_id text,
  p_after bigint default 0,
  p_limit integer default 500
) returns jsonb
  language plpgsql stable security definer set search_path = ''
as $$
declare
  v_limit integer := least(greatest(coalesce(p_limit, 500), 1), 1000);
  v_rows jsonb;
  v_count integer;
  v_last bigint;
begin
  if not private.can_access_store(p_store_id) then
    raise exception 'no access to store %', p_store_id using errcode = '42501';
  end if;

  with changes as (
    select server_seq, 'stores'::text as tbl,
           to_jsonb(t) - 'server_seq' - 'updated_by_device' - 'organization_id' as row
      from public.stores t
     where id = p_store_id and server_seq > p_after
    union all
    select server_seq, 'categories'::text as tbl,
           to_jsonb(t) - 'server_seq' - 'updated_by_device' as row
      from public.categories t
     where store_id = p_store_id and server_seq > p_after
    union all
    select server_seq, 'units'::text as tbl,
           to_jsonb(t) - 'server_seq' - 'updated_by_device' as row
      from public.units t
     where store_id = p_store_id and server_seq > p_after
    union all
    select server_seq, 'items'::text as tbl,
           to_jsonb(t) - 'server_seq' - 'updated_by_device' as row
      from public.items t
     where store_id = p_store_id and server_seq > p_after
    union all
    select server_seq, 'suppliers'::text as tbl,
           to_jsonb(t) - 'server_seq' - 'updated_by_device' as row
      from public.suppliers t
     where store_id = p_store_id and server_seq > p_after
    union all
    select server_seq, 'supplier_prices'::text as tbl,
           to_jsonb(t) - 'server_seq' - 'updated_by_device' as row
      from public.supplier_prices t
     where store_id = p_store_id and server_seq > p_after
    union all
    select server_seq, 'price_history'::text as tbl,
           to_jsonb(t) - 'server_seq' - 'updated_by_device' as row
      from public.price_history t
     where store_id = p_store_id and server_seq > p_after
    union all
    select server_seq, 'stock_movements'::text as tbl,
           to_jsonb(t) - 'server_seq' - 'updated_by_device' as row
      from public.stock_movements t
     where store_id = p_store_id and server_seq > p_after
    union all
    select server_seq, 'purchase_orders'::text as tbl,
           to_jsonb(t) - 'server_seq' - 'updated_by_device' as row
      from public.purchase_orders t
     where store_id = p_store_id and server_seq > p_after
    union all
    select server_seq, 'purchase_order_lines'::text as tbl,
           to_jsonb(t) - 'server_seq' - 'updated_by_device' as row
      from public.purchase_order_lines t
     where store_id = p_store_id and server_seq > p_after
    union all
    select server_seq, 'goods_receipts'::text as tbl,
           to_jsonb(t) - 'server_seq' - 'updated_by_device' as row
      from public.goods_receipts t
     where store_id = p_store_id and server_seq > p_after
    union all
    select server_seq, 'goods_receipt_lines'::text as tbl,
           to_jsonb(t) - 'server_seq' - 'updated_by_device' as row
      from public.goods_receipt_lines t
     where store_id = p_store_id and server_seq > p_after
    union all
    select server_seq, 'notifications'::text as tbl,
           to_jsonb(t) - 'server_seq' - 'updated_by_device' as row
      from public.notifications t
     where store_id = p_store_id and server_seq > p_after
    union all
    select server_seq, 'employees'::text as tbl,
           to_jsonb(t) - 'server_seq' - 'updated_by_device' as row
      from public.employees t
     where store_id = p_store_id and server_seq > p_after
    union all
    select server_seq, 'employee_credentials'::text as tbl,
           to_jsonb(t) - 'server_seq' - 'updated_by_device' as row
      from public.employee_credentials t
     where store_id = p_store_id and server_seq > p_after
    union all
    select server_seq, 'payroll_periods'::text as tbl,
           to_jsonb(t) - 'server_seq' - 'updated_by_device' as row
      from public.payroll_periods t
     where store_id = p_store_id and server_seq > p_after
    union all
    select server_seq, 'attendances'::text as tbl,
           to_jsonb(t) - 'server_seq' - 'updated_by_device' as row
      from public.attendances t
     where store_id = p_store_id and server_seq > p_after
    union all
    select server_seq, 'attendance_sessions'::text as tbl,
           to_jsonb(t) - 'server_seq' - 'updated_by_device' as row
      from public.attendance_sessions t
     where store_id = p_store_id and server_seq > p_after
    union all
    select server_seq, 'attendance_pauses'::text as tbl,
           to_jsonb(t) - 'server_seq' - 'updated_by_device' as row
      from public.attendance_pauses t
     where store_id = p_store_id and server_seq > p_after
    union all
    select server_seq, 'busy_dates'::text as tbl,
           to_jsonb(t) - 'server_seq' - 'updated_by_device' as row
      from public.busy_dates t
     where store_id = p_store_id and server_seq > p_after
  ), page as (
    select * from changes order by server_seq limit v_limit + 1
  )
  select coalesce(jsonb_agg(jsonb_build_object(
           'seq', server_seq, 'table', tbl, 'row', row) order by server_seq)
           filter (where rn <= v_limit), '[]'::jsonb),
         count(*),
         max(server_seq) filter (where rn <= v_limit)
    into v_rows, v_count, v_last
    from (select *, row_number() over (order by server_seq) as rn
            from page) numbered;

  return jsonb_build_object(
    'changes', v_rows,
    'next_after', coalesce(v_last, p_after),
    'has_more', v_count > v_limit
  );
end;
$$;

revoke execute on function public.pull_changes(text, bigint, integer)
  from anon, public;
grant execute on function public.pull_changes(text, bigint, integer)
  to authenticated;
