-- The pointage audit joins the sync (SYNC_PERSONNEL_PLAN.md, step 2; app
-- schema v21).
--
-- - `stores.business_day_auto_open_minutes`: when a journée de service may
--   open by itself, 05:00 by default — what every store read before.
-- - `attendance_sessions.exit_set_by_employee_id`: who entered an exit in
--   the employee's place; null on every existing session.
-- - `notifications`: the three columns of a signalement (step 3).
-- - `business_days`, the journées de service, mirrored like every synced
--   table (generated by tool/generate_server_schema.py), and `pull_changes`
--   redefined to return them.
--
-- Two journées for one store and date stay two rows here: the server is a
-- mirror. Every device keeps the one with the smaller id (rule P5).

alter table public.stores
  add column business_day_auto_open_minutes bigint not null default 300;

alter table public.attendance_sessions
  add column exit_set_by_employee_id text;

-- Signalements (step 3): the employee one is about, and when a manager and
-- the owner first read it — read separately.
alter table public.notifications
  add column related_employee_id text,
  add column read_by_manager_at timestamptz,
  add column read_by_owner_at timestamptz;

create table public.business_days (
  updated_at timestamptz not null,
  deleted_at timestamptz,
  id text not null,
  store_id text not null references public.stores (id),
  date timestamptz not null,
  opened_at timestamptz not null,
  opened_by_employee_id text,
  closed_at timestamptz,
  closed_by_employee_id text,
  server_seq bigint not null,
  updated_by_device text,
  primary key (id)
);
create index business_days_pull on public.business_days (store_id, server_seq);
create trigger business_days_seq before insert or update on public.business_days
  for each row execute function private.stamp_server_seq();
create trigger business_days_store_change after insert or update on public.business_days
  for each row execute function private.note_store_change('store_id');
alter table public.business_days enable row level security;
create policy business_days_read on public.business_days for select to authenticated
  using (private.can_access_store(store_id));
revoke insert, update, delete, truncate on public.business_days
  from anon, authenticated;
revoke all on public.business_days from anon;
insert into private.sync_tables (name, key_columns, store_column)
  values ('business_days', array['id'],
          'store_id');

-- Everything in one store that changed after `p_after`, oldest first, at
-- most `p_limit` rows. The caller saves `next_after` and asks again while
-- `has_more` is true. Deleted rows come back too (with `deleted_at` set):
-- that is how a device learns about a delete.
create or replace function public.pull_changes(
  p_store_id text,
  p_after bigint default 0,
  p_limit integer default 500
) returns jsonb
  language plpgsql stable security definer set search_path = ''
as $$
declare
  v_limit integer := least(greatest(coalesce(p_limit, 500), 1), 1000);
  v_rows jsonb;
  v_count integer;
  v_last bigint;
begin
  if not private.can_access_store(p_store_id) then
    raise exception 'no access to store %', p_store_id using errcode = '42501';
  end if;

  with changes as (
    select server_seq, 'stores'::text as tbl,
           to_jsonb(t) - 'server_seq' - 'updated_by_device' - 'organization_id' as row
      from public.stores t
     where id = p_store_id and server_seq > p_after
    union all
    select server_seq, 'categories'::text as tbl,
           to_jsonb(t) - 'server_seq' - 'updated_by_device' as row
      from public.categories t
     where store_id = p_store_id and server_seq > p_after
    union all
    select server_seq, 'units'::text as tbl,
           to_jsonb(t) - 'server_seq' - 'updated_by_device' as row
      from public.units t
     where store_id = p_store_id and server_seq > p_after
    union all
    select server_seq, 'items'::text as tbl,
           to_jsonb(t) - 'server_seq' - 'updated_by_device' as row
      from public.items t
     where store_id = p_store_id and server_seq > p_after
    union all
    select server_seq, 'suppliers'::text as tbl,
           to_jsonb(t) - 'server_seq' - 'updated_by_device' as row
      from public.suppliers t
     where store_id = p_store_id and server_seq > p_after
    union all
    select server_seq, 'supplier_prices'::text as tbl,
           to_jsonb(t) - 'server_seq' - 'updated_by_device' as row
      from public.supplier_prices t
     where store_id = p_store_id and server_seq > p_after
    union all
    select server_seq, 'price_history'::text as tbl,
           to_jsonb(t) - 'server_seq' - 'updated_by_device' as row
      from public.price_history t
     where store_id = p_store_id and server_seq > p_after
    union all
    select server_seq, 'stock_movements'::text as tbl,
           to_jsonb(t) - 'server_seq' - 'updated_by_device' as row
      from public.stock_movements t
     where store_id = p_store_id and server_seq > p_after
    union all
    select server_seq, 'purchase_orders'::text as tbl,
           to_jsonb(t) - 'server_seq' - 'updated_by_device' as row
      from public.purchase_orders t
     where store_id = p_store_id and server_seq > p_after
    union all
    select server_seq, 'purchase_order_lines'::text as tbl,
           to_jsonb(t) - 'server_seq' - 'updated_by_device' as row
      from public.purchase_order_lines t
     where store_id = p_store_id and server_seq > p_after
    union all
    select server_seq, 'goods_receipts'::text as tbl,
           to_jsonb(t) - 'server_seq' - 'updated_by_device' as row
      from public.goods_receipts t
     where store_id = p_store_id and server_seq > p_after
    union all
    select server_seq, 'goods_receipt_lines'::text as tbl,
           to_jsonb(t) - 'server_seq' - 'updated_by_device' as row
      from public.goods_receipt_lines t
     where store_id = p_store_id and server_seq > p_after
    union all
    select server_seq, 'notifications'::text as tbl,
           to_jsonb(t) - 'server_seq' - 'updated_by_device' as row
      from public.notifications t
     where store_id = p_store_id and server_seq > p_after
    union all
    select server_seq, 'employees'::text as tbl,
           to_jsonb(t) - 'server_seq' - 'updated_by_device' as row
      from public.employees t
     where store_id = p_store_id and server_seq > p_after
    union all
    select server_seq, 'employee_credentials'::text as tbl,
           to_jsonb(t) - 'server_seq' - 'updated_by_device' as row
      from public.employee_credentials t
     where store_id = p_store_id and server_seq > p_after
    union all
    select server_seq, 'payroll_periods'::text as tbl,
           to_jsonb(t) - 'server_seq' - 'updated_by_device' as row
      from public.payroll_periods t
     where store_id = p_store_id and server_seq > p_after
    union all
    select server_seq, 'attendances'::text as tbl,
           to_jsonb(t) - 'server_seq' - 'updated_by_device' as row
      from public.attendances t
     where store_id = p_store_id and server_seq > p_after
    union all
    select server_seq, 'attendance_sessions'::text as tbl,
           to_jsonb(t) - 'server_seq' - 'updated_by_device' as row
      from public.attendance_sessions t
     where store_id = p_store_id and server_seq > p_after
    union all
    select server_seq, 'attendance_pauses'::text as tbl,
           to_jsonb(t) - 'server_seq' - 'updated_by_device' as row
      from public.attendance_pauses t
     where store_id = p_store_id and server_seq > p_after
    union all
    select server_seq, 'busy_dates'::text as tbl,
           to_jsonb(t) - 'server_seq' - 'updated_by_device' as row
      from public.busy_dates t
     where store_id = p_store_id and server_seq > p_after
    union all
    select server_seq, 'business_days'::text as tbl,
           to_jsonb(t) - 'server_seq' - 'updated_by_device' as row
      from public.business_days t
     where store_id = p_store_id and server_seq > p_after
  ), page as (
    select * from changes order by server_seq limit v_limit + 1
  )
  select coalesce(jsonb_agg(jsonb_build_object(
           'seq', server_seq, 'table', tbl, 'row', row) order by server_seq)
           filter (where rn <= v_limit), '[]'::jsonb),
         count(*),
         max(server_seq) filter (where rn <= v_limit)
    into v_rows, v_count, v_last
    from (select *, row_number() over (order by server_seq) as rn
            from page) numbered;

  return jsonb_build_object(
    'changes', v_rows,
    'next_after', coalesce(v_last, p_after),
    'has_more', v_count > v_limit
  );
end;
$$;

revoke execute on function public.pull_changes(text, bigint, integer)
  from anon, public;
grant execute on function public.pull_changes(text, bigint, integer)
  to authenticated;
